name: Deploy Supabase Functions

on:
  push:
    paths:
      - 'supabase/functions/**' # Edge Functions 관련 파일 변경 시 실행
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Install Supabase CLI
        run: curl -L https://supabase.com/cli/install | sh

      - name: Authenticate Supabase CLI
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase login --token $SUPABASE_ACCESS_TOKEN

      - name: Deploy Edge Functions
        run: |
          cd supabase/functions
          for dir in */ ; do
            supabase functions deploy "${dir%/}"
          done
